import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import TrendingProducts from "@/components/TrendingProducts";
import NavbarWrapper from "@/components/NavbarWrapper";
import FooterWrapper from "@/components/FooterWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VibeStore - Your Ultimate Shopping Destination",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-white text-black dark:bg-slate-900 dark:text-white transition-colors duration-300 flex flex-col">
        <Providers>
          <NavbarWrapper />
          <main className="flex-grow">{children}</main>
          <FooterWrapper/>
        </Providers>
      </body>
    </html>
  );
}
